services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "6001:6001"
    environment:
      DB_HOST: db
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: secret

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "9000:80"


  python:
    build:
      context: ./python
    container_name: python
    depends_on:
      - redis
    command: ["python3", "main.py"]

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redis

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:8000"

  services:
    caddy:
      image: caddy:alpine
      container_name: caddy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config

  volumes:
    caddy_data:
    caddy_config:



networks:  
  default: 
    driver: bridge

