services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8010:8010"  # Remove if not needed
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: secret

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python
    volumes:
      - ./python:/app
    depends_on:
      - redis
    command: ["python3", "main.py"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8090:80"

volumes:
  redis_data: