services:
      
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php
    networks:
      - web
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: secret
      
  reverb:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reverb
    networks:
      - web
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    environment:
      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: your_app_id
      REVERB_APP_KEY: your_app_key
      REVERB_APP_SECRET: your_app_secret
      REVERB_HOST: 0.0.0.0
      REVERB_PORT: 8080
      REVERB_SCHEME: http
    depends_on:
      - php
      - redis
    volumes:
      - ./backend:/var/www/html
  caddy:
    image: caddy:alpine
    container_name: caddy
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python
    networks:
      - web
    volumes:
      - ./python:/app
    depends_on:
      - redis
    command: ["python3", "tick_streamer.py"]

  redis:
    image: redis:7
    container_name: redis
    networks:
      - web
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: mysql:8
    container_name: db
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    networks:
      - web
    environment:
      PMA_HOST: db
    ports:
      - "8090:80"

volumes:
  redis_data:
  db_data:
    driver: local
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge